import React, { useState } from 'react';
import Summary from './Summary.jsx';
import './UploadPage.css';

function UploadPage() {

// UploadPage is a function component that renders the Upload page, handles file uploads and prints the summary. 

// State Variables:
// - file: Stores the user's selected file.
// - summary: Stores the summary generated by the backend server.
// - message: Displays a message that informs the user.
// - isReady: We use this variable, so we can conditional rendering the summary (if its true summary is printed)

// Event Handlers:
// - selectFile(event): Triggered when the user selects a file from the upload form.
//   - Updates the file state with the selected file
//   - Displays an error message if there is no file selected
// - uploadFile(event): Triggered when a user clicks the "Upload" button. 
//   - Sends the file to the backend.
//   - Updates the summary state with the response (generated summary) from server.
//   - Displays an error message if the upload fails.
// - printSummary(event): Triggered when user click the Summary button
//   - is responsible for printing the summary in the UI

  const [file, setFile] = useState(null);  
  const [summary, setSummary] = useState("");  
  const [message, setMessage] = useState("Please select a file to upload.");
  const [isReady, setIsReady] = useState(false);  

  const selectFile = (event) => {
    const userFile = event.target.files[0]; 
    setSummary("");
    setIsReady(false)
    if (userFile) {
      setFile(userFile);
      setMessage("File selected.");
    }
    else {
      setFile(null);
      setMessage("Please select a file for upload.");
    }
  }
    
  const uploadFile = async (event) => {
    setSummary("");
    setIsReady(false)
    setMessage("Wait for file uploading and summary generation.");
    event.preventDefault();
    if (!file) {
      setMessage("Please select a file to upload.");
      return;
    }
    const formData = new FormData();
    formData.append('userfile', file); 
    
    try {
      const response = await fetch('http://localhost:5000/summarize', {
        method: 'POST',
        body: formData
      });
      const data = await response.json();
      if (response.ok) {
        console.log('Summary generated successfully!');
        setMessage('Summary generated successfully!');
        setSummary(data.summary);
      } 
      else {
        console.log("Failed to upload the file. Status:",response.status);
        setMessage(data.error);
      }
    } 
    catch (err) {
      console.log("An error occured.",err);
      setMessage("An error occured.");
    } 
  }

  // runs only if summary is available
  const printSummary = async (event) => {
    event.preventDefault(); 
    if (summary) {
      setMessage("Your summary is here!");
      setIsReady(true);
      return;
    }
    else
      setMessage("Please select and upload a file.");
  }

  return (
    <div>
      <div className='upload-container'>
        <form onSubmit={uploadFile}>
          <input 
            className='user-file'
            type="file" 
            onChange={selectFile} 
            accept=".pdf"
          />
          <div className='button-container'>
            <button onClick={uploadFile}>Uploading</button>
            <button onClick={printSummary}>Summarize</button>
          </div>
        </form>
      </div>
      <div className="message-container">
        <p>{message}</p>
      </div>
      <Summary summary={summary} isReady={isReady}/>
    </div>
  );
}

export default UploadPage;

