name: CI Pipe 

on:
  push:
    branches:
      - main   

jobs:
  build-test:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout Code  
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2  

      - name: Build Docker Images 
        run: docker compose build  

      - name: Start Services  
        env:
          OPENAI_API_KEY: ${secrets.OPENAI_API_KEY}  # Inject the OpenAI API Key as an env variable
        run: docker compose up -d  

      - name: Stop Services  
        run: docker compose down  


# name: CI pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-backend:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           pip install -r backend/app/requirements.txt

#       - name: Run tests with pytest
#         run: |
#           pytest backend/app  